server:
  port: 8000

ribbon:
  #指的是建立连接所用的时间,适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
spring:
  application:
    name: service-gateway #此实例注册到eureka服务端的name
  redis:
    host: 47.107.97.99
    port: 6379
    password: 0B_#8V$!VWAKGXJ1
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: -1ms
        min-idle: 10
    timeout: 1000ms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://SERVER-USER
          predicates:
            - Path=/user/**

